### ISSUE TITLE
Question or feature: adding arguments to executable 

### ISSUE THREAD

**Issue by dataselfservice** [ko-build/ko#1018]
Hi, 

any possibility to add arguments to the executable, e.g. appending them to entrypoint?

Is that breaking some principle, in case it is implemented?

**Comment by dataselfservice** [comment]
The triggering need is to be able to run <my_go_exec> <args...> at runtime, with custom <args...>. In detail, <my_go_exec> needs a config file: it runs with `<my_go_exec> -c <config_file_with_path>` , and `<config_file_with_path>` can change. I currently edit the docker image entrypoint and add that there. Not best likely. Might be using env variables is a better option.

And, no, this is not about setting args to `go build`.

**Comment by dataselfservice** [comment]
the case is a bit different: the image yes tested on (docker), but then loaded to kubernetes clusters, requiring different `<config>`. My choice is either handle it with differnet executables, which I do not like because testing should be done on exactly same exec, or change entrypoint in the docker image (which is the loaded into kubenetes). Note: the same image is pushed to the docker registry for prod deployment.

Again I'm not a pro here, can I add `-c <config>` to the kubernetes yaml deploy. Or?

**Comment by dataselfservice** [comment]
Something like this fits my purpose, but not sure it is a good merge || there are better solutions: https://github.com/ko-build/ko/pull/1023

**Comment by imjasonh** [comment]
> Again I'm not a pro here, can I add `-c <config>` to the kubernetes yaml deploy. Or?

You can!

```
containers:
- name: app
  image: ko://github.com/my/app/cmd/server
  args: ['extra', 'args', '--and', '--flags']
```

This will start the container and run the `entrypoint`, with the given args, e.g., `/ko-app/server extra args --and --flags`, just as if you'd done `docker run <image> extra args --and --flags`.

Give it a shot and let me know if it works. I'm not hugely opposed to adding entrypoint args, but I'd rather not if it turns out you don't need to yet.

**Comment by dataselfservice** [comment]
> args: ['extra', 'args', '--and', '--flags']
...oh. You made my day. I can happily now use mainstream `ko` with your approach. Thanks!
