### ISSUE TITLE
Provide write permissions to container FS to golang app running in a distroless container

### ISSUE THREAD

**Issue by unmarshall** [ko-build/ko#1066]
Hello,

We have a golang app for which we use skaffold and ko to build an image. KO by default uses a distroless base image. Upon inspecting that image it seems that `nonroot` user does not have write permissions to anything except `/tmp` directory which is a problem. The application in question writes a configuration file to `/etc` and for obvious reasons it used to work when using non-distroless containers. When using docker to build the image we could use `chown` along with `copy` command (https://docs.docker.com/engine/reference/builder/#copy) but i do not find any such command/configuration in KO. 

The following works with a Dockerfile:
```
FROM golang:1.20 as builder
WORKDIR /go/src/github.com/org/myapp
COPY . .

RUN mkdir -p /var/myapp/config

# Build
RUN make build

FROM gcr.io/distroless/static-debian11:nonroot AS myapp
WORKDIR /

COPY --from=builder --chown=nonroot:nonroot /var/myapp/config /var/myapp/config
COPY --from=builder /go/src/github.com/org/myapp/bin/myapp /myapp
ENTRYPOINT ["/myapp"]
```

Any help would be appreciated.

**Comment by unmarshall** [comment]
I have already tried to use `gcr.io/distroless/static-debian11:nonroot` with KO but even with this image by default you do not have permissions and that is the reason i had to explicitly create an empty dir in the builder step and  change the ownership while copying that folder from the builder to the final image. Same problem for all distroless images with nonroot users.

**Comment by imjasonh** [comment]
This isn't really a `ko` issue. If you choose a base image that runs as a user that has permission to write to `/etc`, things should work fine. Neither the default base image or `gcr.io/distroless/static-debian11:nonroot` do that, but you can choose or build a base image that does allow that.
