### ISSUE TITLE
Push an image with specific version number instead of latest?

### ISSUE THREAD

**Issue by samlaf** [ko-build/ko#1072]
Is it possible to push an image with a specific version number. Adding the `--bare` flag publishes to `latest` version number by default. Trying to add the version number like `image_repo:0.0.1` results in error:
```
Error: error creating publisher: failed to parse "ghcr.io/samlaf/prometheus-scraper:0.0.1" as repository: repository can only contain the characters `abcdefghijklmnopqrstuvwxyz0123456789_-./`: ghcr.io/samlaf/prometheus-scraper:0.0.1
make: *** [ko-build] Error 1
```

**Comment by akowasch** [comment]
To specify the image tag `0.0.1` instead of `latest` you can use the `--tags` option of the ko CLI together with the `--bare` option.

```
export KO_DOCKER_REPO="ghcr.io/samlaf/prometheus-scraper"
ko build --bare --tags 0.0.1
```
