### ISSUE TITLE
feat: custom URL for fetching latest ko binary

### ISSUE THREAD

**Issue by kranurag7** [ko-build/ko#1086]
It will be good to have a `install.sh` mapped to `get.ko.build` which I can remember and invoke directly as a command using curl or wget.

**Comment by imjasonh** [comment]
Thanks for the suggestion, but I'd prefer not to recommend this kind of thing in general, and instead have folks rely on a package manager or something like [`setup-ko`](https://github.com/ko-build/setup-ko) instead.

Encouraging folks to blindly run scripts from the internet invites supply chain attacks and paints a target on whatever workflow generates install.sh or serves `get.ko.build`.

**Comment by kranurag7** [comment]
Thanks, @imjasonh, I agree with you. I need to stop executing and looking for easy one-liner to execute on my systems. This is becoming a bad habit on my end.
