### ISSUE TITLE
Skip go build if no files have changed since a previous build

### ISSUE THREAD

**Issue by ecordell** [ko-build/ko#1116]
I started to switch some docker-compose builds over to use `ko` instead for use in a local `kind` cluster.

When there are code changes, images tend to build much faster with ko (~80% in this case):

```sh
$ time zsh -c "docker-compose build spicedb-operator; time kind load docker-image authzed/spicedb-operator:dev"
zsh -c   0.87s user 1.09s system 14% cpu 13.035 total
```
vs
```sh
$ time mage dev:ko
mage dev:ko  3.92s user 2.41s system 77% cpu 8.177 total
```

But when there are no code changes at all, docker knows it can skip the `go build` line entirely, whereas `ko` seems to always call `go build`:

```sh
$ time zsh -c "docker-compose build spicedb-operator; kind load docker-image authzed/spicedb-operator:dev --name=authzed-dev"
...                                                                                                             0.0s
 => CACHED [spicedb-operator builder 5/5] RUN --mount=type=cache,target=/root/.cache/go-build --mount=type=cache,target=/go/pkg/mod go build ./cmd/...          0.0s
...
zsh -c   0.17s user 0.11s system 10% cpu 2.695 total
```
vs
```sh
$ time mage dev:ko
mage dev:ko  3.75s user 1.96s system 114% cpu 4.976 total
```

It would be nice if ko could also know when no input files have changed and skip the go build. Is there some reason I shouldn't want ko to do this?

(I'm calling ko as a library for this but I saw the same behavior running the cli tool)

**Comment by evankanderson** [comment]
I'm assuming that the way that you figure that no files have changed is that `go build` figures out that no files have changed, and `ko` itself doesn't actually track whether files have changed.  Note that a local Go build may also be sensitive to changes to the cached Go modules in `~/go/pkg/mod`, whereas Docker will not.
