### ISSUE TITLE
Unable to run git commands inside container image

### ISSUE THREAD

**Issue by vinamra28** [ko-build/ko#1153]
### Feature request

Container image of `ko` should have git binary present and the entrypoint of image should be `bash` or `sh` instead of `ko`

### Use case

With recent versions of git, there is a need to mark the repository as safe repository using
```sh
git config --global --add safe.directory "/path/to/clonedrepo"
```
While this can be achieved in location environment, in a CI/CD environment where each step runs as a container, more specifically in Tekton, the same step has to be repeated before doing anything and `ko` Container image doesn't gives that flexibility to run the following git command before executing the `ko` build

### Steps to reproduce in Tekton

1. Setup Tekton in your kubernetes cluster (if not present)
1. Install latest version of `git-clone` Task from https://github.com/tektoncd/catalog
1. Install `ko` Task from the same repository
1.  Apply the PVC from https://github.com/tektoncd/catalog/blob/main/task/ko/0.1/tests/resources.yaml
1. Create the Pipeline, PipelineRun using https://github.com/tektoncd/catalog/blob/main/task/ko/0.1/tests/run.yaml
1. Check the logs. It should error out with
    ```
    2023/09/17 16:50:38 Using base 
    golang:1.21@sha256:cffaba795c36f07e372c7191b35ceaae114d74c31c3763d442982e3a4df3b39e for github.com/google/ko
    2023/09/17 16:50:39 Using build config ko for github.com/google/ko
    2023/09/17 16:50:39 Building github.com/google/ko for linux/amd64
    Error: failed to publish images: error building "ko://github.com/google/ko": build: go build: exit status 1: error obtaining VCS 
    status: exit status 128
        Use -buildvcs=false to disable VCS stamping.
    ```

**Comment by vinamra28** [comment]
@imjasonh @jonjohnsonjr please let me know if the ask here is valid or not. Also if the same can be achieved in a different way, please do suggest 😅

**Comment by vinamra28** [comment]
@imjasonh @jonjohnsonjr in case you missed this 😅

**Comment by vinamra28** [comment]
@cpanato ^^

**Comment by cpanato** [comment]
if you set the entrypoint to "" then you can entry with `/bin/sh` and then you will have access to shell and git

```
$ docker run -it --entrypoint=''  ghcr.io/ko-build/ko:latest /bin/sh
# git
usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           [--super-prefix=<path>] [--config-env=<name>=<envvar>]
           <command> [<args>]

These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone     Clone a repository into a new directory
   init      Create an empty Git repository or reinitialize an existing one

work on the current change (see also: git help everyday)
   add       Add file contents to the index
   mv        Move or rename a file, a directory, or a symlink
   restore   Restore working tree files
   rm        Remove files from the working tree and from the index

examine the history and state (see also: git help revisions)
   bisect    Use binary search to find the commit that introduced a bug
   diff      Show changes between commits, commit and working tree, etc
   grep      Print lines matching a pattern
   log       Show commit logs
   show      Show various types of objects
   status    Show the working tree status

grow, mark and tweak your common history
   branch    List, create, or delete branches
   commit    Record changes to the repository
   merge     Join two or more development histories together
   rebase    Reapply commits on top of another base tip
   reset     Reset current HEAD to the specified state
   switch    Switch branches
   tag       Create, list, delete or verify a tag object signed with GPG

collaborate (see also: git help workflows)
   fetch     Download objects and refs from another repository
   pull      Fetch from and integrate with another repository or a local branch
   push      Update remote refs along with associated objects

'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
See 'git help git' for an overview of the system.
#
```

**Comment by vinamra28** [comment]
@cpanato I doubt if I can specify the same in Tekton  😅

**Comment by evankanderson** [comment]
You can specify the `entrypoint` and `cmd` in docker as `command` and `args` in Kubernetes and Tekton; see the following example:

https://tekton.dev/docs/pipelines/tasks/#inspecting-the-file-structure

```
- name: build-and-push-1
  image: ubuntu
  command:
    - /bin/bash
  args:
    - -c
    - |
      set -ex
      find /workspace
```

If you use a base image which includes git and bash, you should be able to do similar sorts of things.

**Comment by vinamra28** [comment]
@evankanderson, since this image is getting used in [`ko` Tekton Task present in catalog](https://github.com/tektoncd/catalog/blob/main/task/ko/0.1/ko.yaml#L19), I am not willing to modify the base image and take the overhead of maintaining a new image
