### ISSUE TITLE
OrbStack support on MacOS

### ISSUE THREAD

**Issue by yodamad** [ko-build/ko#1169]
Hi,

I'm trying to run ko on my macbook where I use [OrbStack](https://orbstack.dev/) to run containers

I've tried to run
```bash
ko build -L .
```
and I got the following error :
```
2023/10/25 17:38:36 Using base cgr.dev/chainguard/static:latest@sha256:ef5add7fd46cf1ce7d33d6de517833ac5c7e749db9b15249f9c472a772f3af27 for go-sample
2023/10/25 17:38:37 Building go-sample for linux/amd64
2023/10/25 17:38:38 Loading registry.gitlab.com/xxx/xxx/xxx/go-sample-3c4fa4489387e6bab887f7869a2a235d:291584a8d900b3cfc243454f5d1fa78f03b81e9e2e78f7818980810ec7de92d8
2023/10/25 17:38:38 daemon.Write response:
Error: failed to publish images: error publishing ko://go-sample: error loading image: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

If I try to access my docker daemin, it's working well
```bash
$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

For information, I'm running ko in version `0.15.0`

**Comment by russellhaering** [comment]
For what its worth, this is working for me with ko `v0.15.1` and OrbStack `1.1.0` - but I don't think the version difference is what fixed it.

My guess is that it relates to this: https://docs.orbstack.dev/docker/#docker-context-socket

It seems like OrbStack's docker daemon listens on a Docker socket at `~/.orbstack/run/docker.sock`, then symlinks that at `/var/run/docker.sock`. So the quick fix is probably to either run OrbStack as an admin, or create that symlink yourself.

I don't know enough about `ko` to have a sense of whether it should be able to use Docker contexts.
