### ISSUE TITLE
ko doesn't work with toolchain directive in go.mod

### ISSUE THREAD

**Issue by upodroid** [ko-build/ko#1184]
@imjasonh @mattmoor 

build log https://github.com/knative-extensions/security-guard/actions/runs/6999709429/job/19039352898
PR: https://github.com/knative-extensions/security-guard/pull/263

```
Error: error processing import paths in "config/deploy/guard-service.yaml": error resolving image references: found strict reference but ko://knative.dev/security-guard/cmd/guard-service is not a valid import path: error loading package from knative.dev/security-guard/cmd/guard-service: err: exit status 1: stderr: go: errors parsing go.mod:
/home/runner/work/security-guard/security-guard/go.mod:5: unknown directive: toolchain
```

**Comment by mattmoor** [comment]
Could this just be that `ko` needs to be rebuilt with a modern version of the go stdlib?

**Comment by imjasonh** [comment]
This seems like a likely explanation. The error seems to be coming from here, where we call `packages.Load` which comes from the stdlib the binary was built with:

https://github.com/ko-build/ko/blob/59a676e42450cb9019e06ef8da9b1280b27ccad6/pkg/build/gobuild.go#L215

The good news is that we're building with 1.21 now, since #1137, which just needs to be released.

**Comment by upodroid** [comment]
> The good news is that we're building with 1.21 now, since #1137, which just needs to be released.

That PR was included in the 0.15.1 release which the action is installing but the error is still there. hmm 😕

**Comment by imjasonh** [comment]
Weird, I'm not able to reproduce with the latest ko

```
$ ko version
0.15.1
$ ko build ./cmd/guard-service/
2023/11/27 22:37:33 Building knative.dev/security-guard/cmd/guard-service for linux/amd64
2023/11/27 22:37:49 Publishing gcr.io/jason-chainguard/guard-service-47f58423958863b1c974ec4e098984f3:latest
2023/11/27 22:38:11 existing blob: sha256:250c06f7c38e52dc77e5c7586c3e40280dc7ff9bb9007c396e06d96736cf8542
2023/11/27 22:38:13 pushed blob: sha256:d9cdc672ff75d2eb63aa285cae4155be88829798d244518fd3e60da60f9fb2f4
2023/11/27 22:38:13 pushed blob: sha256:82d2e829cf186480df810fb120895daa35c86e73f45e67e4849dbf793a18d635
...
```

Is it possible your Go version is pre-1.21?

```
$ go version
go version go1.21.4 darwin/arm64
```

**Comment by davidhadas** [comment]
Thanks!
It seems the problem was indeed that the failure took place under go 1.19.
(e2e test was using  1.19)
Fixed by https://github.com/knative-extensions/security-guard/pull/265

**Comment by imjasonh** [comment]
Great to hear! So it's more about the Go version installed than the `ko` version, which is nice.

Thanks for following up!
