### ISSUE TITLE
[Fly.io] Image does not need to be public

### ISSUE THREAD

**Issue by userbradley** [ko-build/ko#1186]
In the docs the below is stated:

https://github.com/ko-build/ko/blob/f37f2d18d1e42b0c0fdcf5da2832a57878fd63d6/docs/deployment.md?plain=1#L27-L33

This is not correct on the image needing to be public. You are able to use Fly.io's docker registry, and push by logging in with `fly auth docker`

I guess it's out of scope for this document to include that, but I thought it's something worth raising.

If you have any idea how this could be better explained in the docs, let me know and I'll open a PR

**Comment by imjasonh** [comment]
Sorry for missing this! I can update the docs to make this clearer.

**Comment by userbradley** [comment]
Sure,I'm also happy to open a PR for this too.

All the user needs to do is run `fly auth docker` and then they get the creds for pushing. From there they just set the `KO_DOCKER_REPO` env variable to be the name of their project. 

Users can push to `registry.fly.io/<app-name>:sha` and then use the deploy command as a second step, or they can do (What you already have) as `flyctl launch --image=$(ko build ./cmd/app)`

Let me know if you'd like more clarification, or for me to submit a PR
