### ISSUE TITLE
Pushing to ECR without logging in first doesn't work

### ISSUE THREAD

**Issue by espadolini** [ko-build/ko#1245]
`ko` 0.15.2 fails to push images to ECR from GitHub actions without first running `aws-actions/amazon-ecr-login`.

The "Push to registries/Push to ECR" action in this very repo stopped passing since c23121a99aa900b18d957bfc6898193994aa7c14 (https://github.com/ko-build/ko/actions/runs/7109904995/job/19355555999#step:6:18), so that's the likely culprit.

**Comment by cpanato** [comment]
That failure is because of some IAM changes in the account that removed the access to push, most likely. I cannot confirm 100% because I don't have access. But the test has been failing for a long time now

**Comment by espadolini** [comment]
I've had it fail just like that on a private repo, and work with no changes to the aws side after reverting from ko 0.15.2 to ko 0.15.1 or by adding an `aws-actions/amazon-ecr-login` step before the ko one.

**Comment by cpanato** [comment]
Hmm I see I will take a look

Thanks!
