### ISSUE TITLE
debugging: build command doesn't provide `--debug` on latest ko: consider releasing new version

### ISSUE THREAD

**Issue by Dentrax** [ko-build/ko#1365]
As [Debugging](https://ko.build/features/debugging/) doc mentions `--debug` flag under `How it works` section, I can able to see this flag on [CLI doc ref](https://github.com/ko-build/ko/blob/main/docs/reference/ko_build.md#options), whereas I couldn't see it on `ko build --help` output:

```
$ ko build --help | grep -A5 "Flags:"

Flags:
      --bare                     Whether to just use KO_DOCKER_REPO without additional context (may not work properly with --tags).
  -B, --base-import-paths        Whether to use the base path without MD5 hash after KO_DOCKER_REPO (may not work properly with --tags).
      --disable-optimizations    Disable optimizations when building Go code. Useful when you want to interactively debug the created container.
  -h, --help                     help for build
      --image-label strings      Which labels (key=value) to add to the image.
--
Global Flags:
  -v, --verbose   Enable debug logs
```

```
$ ko version

0.15.4
```

I can see this flag is exist at [AddBuildOptions()](https://github.com/ko-build/ko/blob/main/pkg/commands/options/build.go#L98) on `main` branch. But its not on `v0.15.4` tag.

Do you have any plan to cut a new release soon?

Thanks!

Ref: https://github.com/ko-build/ko/issues/78

**Comment by josephmcasey** [comment]
This issue has been resolved as of version 17.1
<img width="1191" alt="ko-options" src="https://github.com/user-attachments/assets/99d7e6bb-624a-4d51-a7fa-be858ba708ec">
