### ISSUE TITLE
Support for multiple `KO_DOCKER_REPO`?

### ISSUE THREAD

**Issue by bahybintang** [ko-build/ko#1423]
Is there currently support for pushing to multiple `KO_DOCKER_REPO` in a single Ko build? In my case, I need to push the build to multiple repositories without running separate Ko builds, as that would increase the build time.

I attempted to set `KO_DOCKER_REPO` like this, but it didn't work:
```
KO_DOCKER_REPO=localhost:5000/test,localhost:5000/test1
```

Is there a recommended way to push to multiple repositories in one go, or is this feature not supported yet?

**Comment by imjasonh** [comment]
I would recommend pushing to one location, and then copying (e.g., `crane copy`) the image to other locations as needed.

There's some complexity building-and-pushing to multiple locations, for example what if building and pushing to A works but pushing to B works -- should the whole process fail? By separating build-and-push-to-A from copy-A-to-B you get simpler tools (`ko` and `crane` only do one thing each), and better failure handling semantics.
