### ISSUE TITLE
Allow adding custom CA certificates

### ISSUE THREAD

**Issue by kosamson** [ko-build/ko#1424]
To load in custom CA root certificates into a container image, I usually use [this method in a Dockerfile](https://stackoverflow.com/questions/42292444/how-do-i-add-a-ca-root-certificate-inside-a-docker-image). I also recently learned of another possible method using [`SSL_CERT_FILE`](https://go.dev/src/crypto/x509/root_unix.go).

Using Ko, I was able to add my custom CA root certificates by baking them into a custom image and then [overriding the default Ko base image](https://ko.build/configuration/#overriding-base-images) to use the custom image. 

However, given the common use case of adding a custom root CA (ex: accessing sites in a private corporate network with a private corporate CA), I am wondering if loading in custom CA root certificates should have a first-class configuration option within Ko.

**Comment by kosamson** [comment]
I think I found a different workaround by setting [`SSL_CERT_DIR`](https://go.dev/src/crypto/x509/root_unix.go) in combination with Ko's [static assets (kodata)](https://ko.build/features/static-assets/).

[Example implementation](https://github.com/kosamson/ko-private-ca-test)

This avoids needing to make a custom base image, and instead relies on:
1. The CI runner to download the custom CA certificates and store them in the repository under `${REPOSITORY_ROOT}/kodata/`
2. The container runtime / orchestrator to set `SSL_CERT_DIR` equal to `KO_DATA_PATH`

**Comment by kosamson** [comment]
To clarify, the requirement I was looking to satisfy was injecting the custom CA certificates into the container and integrate it with the Go app **without storing the CA certificate(s) in the repository**, which the above workaround satisfies. I think this may work long-term, but I need to do some testing to see if overriding `SSL_CERT_DIR=$KO_DATA_PATH` impacts the default CA certificates.

Based on the Go source, I'm concerned that overriding the [default value](https://github.com/golang/go/blob/master/src/crypto/x509/root_linux.go#L20) will [replace, not append, the certificate directories](https://github.com/golang/go/blob/master/src/crypto/x509/root_unix.go#L53).

**Comment by kosamson** [comment]
I did note in my test that even after overriding `SSL_CERT_DIR`, I was still able to perform a TLS handshake with common public root CAs.

Based on the [Chainguard static image specification](https://images.chainguard.dev/directory/image/static/specifications), SSL_CERT_FILE is already set to `SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt`, so maybe I don't need to worry about adding all possible directories under `SSL_CERT_DIR`?

**Comment by jeffmendoza** [comment]
IMO, one of ko's strengths is its simplicity and streamlined options. As you mentioned, providing the option of allowing your own base image allows customizing the root certs. Expanding ko to encompass root cert options and management would be scope creep, and detract from its appeal.

Thanks for sharing your testing with providing the certs using KO_DATA_PATH, I think others will benefit from this. Possibly this would be a good topic to add a doc about under "Advanced" in the https://ko.build/ docs?

**Comment by kosamson** [comment]
> IMO, one of ko's strengths is its simplicity and streamlined options. As you mentioned, providing the option of allowing your own base image allows customizing the root certs. Expanding ko to encompass root cert options and management would be scope creep, and detract from its appeal.
> 
> Thanks for sharing your testing with providing the certs using KO_DATA_PATH, I think others will benefit from this. Possibly this would be a good topic to add a doc about under "Advanced" in the https://ko.build/ docs?

Understood, avoiding feature/scope creep makes sense and I agree that simplicity is a higher priority. I would definitely be interested in documenting the KO_DATA_PATH method. Let me try setting up the docs dev stuff locally, and then I'll open a PR.

Thank you for reviewing the issue!
