### ISSUE TITLE
Release v0.17.0 binaries has not been generated

### ISSUE THREAD

**Issue by chmouel** [ko-build/ko#1433]
which break the setup-ko actions,

I wonder if it's a chicken and egg kind of thing, since goreleaser action depends on the latest but binaries has not been built yet? cf:

https://github.com/ko-build/ko/actions/runs/11504196400/job/32023168508

```log
++ curl -L -s -u username:*** https://api.github.com/repos/ko-build/ko/releases/latest
++ jq -r .tag_name
+ tag=v0.17.0
Installing ko @ v0.17.0 for Linux
+ os=Linux
+ [[ Linux == \m\a\c\O\S ]]
+ [[ ! -z v0.17.0 ]]
+ echo 'Installing ko @ v0.17.0 for Linux'
+ sudo tar xzf - -C /usr/local/bin ko
+ curl -fsL https://github.com/ko-build/ko/releases/download/v0.17.0/ko_0.17.0_Linux_x86_64.tar.gz

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Error: Process completed with exit code 2.
```

**Comment by vdemeester** [comment]
Turns out, there is probably a "race" condition 😛 
https://github.com/ko-build/ko/actions/runs/11504196400/job/32023168508 it did not generate binaries because it failed on `setup-ko` 😛 

@imjasonh 🙏🏼

**Comment by evankanderson** [comment]
(This is causing https://github.com/ko-build/setup-ko to fail)

**Comment by jonjohnsonjr** [comment]
Introduced here https://github.com/ko-build/ko/commit/61a6c202c83ee2d7480abf590b861c419ba3b58f#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34

Fix here https://github.com/ko-build/ko/pull/1435 and we'd cut a new patch release.

**Comment by cpanato** [comment]
Thanks @jonjohnsonjr for fixing my mess

**Comment by cpanato** [comment]
Relasesed and fixed

@chmouel can you confirm?

**Comment by chmouel** [comment]
all good now, thanks
