### ISSUE TITLE
Define common build tags to consume in `.ko.yaml`

### ISSUE THREAD

**Issue by embano1** [ko-build/ko#493]
Since `.ko.yaml` is likely going to be used for more CI automation and releasing artifacts, it would be great to have access to common build variables, e.g. `date/time` (RFC3339), `commit` (short/long) and perhaps (git) `tag` instead of having to manually create them in the environment to reference them in `.ko.yaml`.

I know this might be out of scope for `ko` due to reasons (e.g. relying on `git`) but just wanted to throw this out so people can find this issue and an answer why this won't be implemented or if this is something you think is useful for the project.

Since `.ko.yaml` is inspired by `goreleaser`, we could reuse some of the standard build-related variables/templates (full list [here](https://goreleaser.com/customization/templates/)).

Example `.ko.yaml` idea:

```yaml
  ldflags:
  - -s -w
  - -extldflags "-static"
  - -X main.commit={{.Env.KO_COMMIT_LONG}}
  - -X main.shortCommit={{.Env.KO_COMMIT_SHORT}}
  - -X main.buildDate={{.Env.KO_DATETIME}}
```

**Comment by nmittler** [comment]
@imjasonh @embano1 I put together a potential fix: https://github.com/ko-build/ko/pull/1307. PTAL when you have a chance.
