### ISSUE TITLE
Generate both SPDX and CycloneDX SBOMs by default

### ISSUE THREAD

**Issue by imjasonh** [ko-build/ko#661]
Today the default is `--sbom=spdx`, we should probably have an `--sbom=all` option and make that the default.

`all` kinda sounds like it includes the `go-version.m` SBOM, and I'm not sure that makes sense since I don't think anybody uses that today. It was mostly there for testing IIRC. Maybe we should just remove that option entirely?

**Comment by mattmoor** [comment]
I hit a similar problem in https://github.com/chainguard-dev/apko/pull/149

**Comment by puerco** [comment]
What about making `--sbom` a string list defaulting to `spdx,cyclonedx`?

**Comment by mattmoor** [comment]
I think that's fine once we resolve the bigger issues with how we store things.

**Comment by imjasonh** [comment]
Sorry, that was my fault, I meant to close it as "not planned".
