### ISSUE TITLE
ko build fails due to undefined packages but go build succeeds

### ISSUE THREAD

**Issue by alexbrand** [ko-build/ko#693]
Ko build fails when using certain packages. I've narrowed it down to one package that produces this behavior: https://github.com/confluentinc/confluent-kafka-go.

I suspect this is an issue with go modules that might have a workaround. But the fact that `go build` succeeds makes me think `ko build` should succeed as well.

Ko version:
```
$ ko version
0.11.2
```

To reproduce:

```bash
mkdir -p /tmp/ko-test
cd /tmp/ko-test
go mod init ko.dev/test
go get github.com/confluentinc/confluent-kafka-go/kafka
cat > main.go <<EOF
package main

import "github.com/confluentinc/confluent-kafka-go/kafka"

func main() {
	kafka.NewProducer(nil)
}
EOF
go build .
KO_DOCKER_REPO=some-repo ko build .
```

Result:
```
2022/04/27 08:28:24 Using base gcr.io/distroless/static:nonroot@sha256:2556293984c5738fc75208cce52cf0a4762c709cf38e4bf8def65a61992da0ad for ko.dev/test
2022/04/27 08:28:24 Building ko.dev/test for linux/amd64
2022/04/27 08:28:25 Unexpected error running "go build": exit status 2
# ko.dev/test
./main.go:6:8: undefined: kafka.NewProducer
Error: failed to publish images: error building "ko://ko.dev/test": exit status 2
2022/04/27 08:28:25 error during command execution:failed to publish images: error building "ko://ko.dev/test": exit status 2
```

**Comment by imjasonh** [comment]
Does `go build` work with CGO disabled? (`CGO_ENABLED=0`)

ko assumes that it won't be using cgo, since this can make base image selection and multiarch harder. It sounds like this Kafka client is a wrapper around a C client.

There are ways to make ko and cgo work together, but it's messy and comes with some limitations.

**Comment by alexbrand** [comment]
Thanks, @imjasonh! Indeed, it fails with CGO disabled. Sounds like ko + CGO is not strictly supported. Should we close this out or do you see any potential action items here?

**Comment by alexbrand** [comment]
Awesome. I'll leave it open to track the docs. I'd be happy to play test subject for those docs once you have them 👍

**Comment by olivierlemasle** [comment]
@imjasonh I'll also be happy to review docs on cgo+ko when ready!

**Comment by imjasonh** [comment]
I'm going to close this as done, but I should mention I recently added an [example](https://github.com/distroless/ko#usage) of using a `ko` image that includes musl libc to build an app that requires cgo.

AFAIK this is the closest we have to the docs I promised in April. Please let me know if you try it out and have problems, either here or in that repo.

**Comment by dio** [comment]
@imjasonh sorry, seems like that example directory is gone now?

**Comment by imjasonh** [comment]
Sorry the example moved to https://github.com/chainguard-images/images/tree/main/images/ko/example
