### ISSUE TITLE
Support packaging go test binaries

### ISSUE THREAD

**Issue by jsok** [ko-build/ko#720]
The ability to package the output of `go test -c` would be quite handy.

My use case here is for integration tests that get built from the same source as the binary, and the resultant image is used in a post-deployment verification phase (e.g. soon to be released [`skaffold verify`](https://github.com/GoogleContainerTools/skaffold/pull/7328) capabilities).

**Comment by imjasonh** [comment]
I bet you could do something like this with `crane append` and `crane mutate --entrypoint` as described in https://github.com/google/go-containerregistry/blob/main/cmd/crane/recipes.md#bundle-directory-contents-into-an-image

**Comment by imjasonh** [comment]
Related: https://github.com/google/ko/issues/96
