### ISSUE TITLE
Output SBOM to file in addition to pushing

### ISSUE THREAD

**Issue by chipzoller** [ko-build/ko#728]
## Problem

In `ko` today, building a container image with the `publish` command, for example, will simultaneously push an SBOM to the same registry. But when attesting an SBOM with `cosign`, the SBOM must be downloaded first. This causes a push-pull-push to occur which is not optimal. 

## Solution

As discussed with @imjasonh in [this Slack discussion](https://kubernetes.slack.com/archives/C01T7DTP65S/p1655132831080329), it may be good to add a flag like `--sbom-path` which would allow simultaneously outputting the SBOM to a file so it can be attested to. Without the flag, there is no behavioral change. With the flag, the existing behavior still remains the same but additionally the SBOM will be written to a file locally.

**Comment by developer-guy** [comment]
@imjasonh I can take over this one if you want.

**Comment by imjasonh** [comment]
Sounds good @developer-guy, thanks! We can discuss more specifics on the PR, or feel free to reach out if you have any questions.

**Comment by chipzoller** [comment]
@developer-guy are you still intending on working this?

**Comment by developer-guy** [comment]
Ah I missed that one, sorry :( OFC, I'd like to take this one too 😋 or if you are interested in it please go head ? 🫶

**Comment by developer-guy** [comment]
Hey @chipzoller, when do you want to output an SBOM? I mean, when `--push=true` or `--push=false`? 

IMHO, we could create another flag like `--sbom-output` to determine where we wanna store the sbom result.

The cases that came to my mind are the followings:

- _--push=true --sbom spdx --sbom-output /tmp/spdx.json_
	> ko will publish the image to a registry but output the sbom into the disk.

- _--push=false --sbom spdx_
    > ko won't publish the image to a registry but publish the sbom to a registry?
  
- _--push=false --sbom spdx --sbom-output /tmp/spdx.json_
	> ko won't publish the image to a registry and output the sbom into the disk.

/cc @imjasonh

**Comment by chipzoller** [comment]
I don't have a full enumeration, but as a user I would want/expect that any command or command combination which results in an SBOM being implicitly pushed to the destination registry would also accept a flag(s) which allow it to be output locally. It seems your suggestions make sense for flag combinations.

**Comment by developer-guy** [comment]
After the discussion we had with @imjasonh, the proper wto implement this feature to ko is by making it that when the`--sbom-dir` flag is used, it should write SBOMlso to a disk no matter specified in the `push` flag.

> we renamed the flas `sbom-dir` to specify the directory so that ko will decide the name of the SBOM file.

/cc @imjasonh
