### ISSUE TITLE
`--cluster` is DEPRECATED, so what's the other way?

### ISSUE THREAD

**Issue by jwcesign** [ko-build/ko#838]
I want to deploy to different kind cluster, but this parameter is DEPRECATED, so what's the other way?

**Comment by jwcesign** [comment]
what about kind cluster?  it's not kubectl parameter, it's used to load image into right kind clusters.

**Comment by jwcesign** [comment]
I see, via env `KIND_CLUSTER_NAME=my-other-cluster`

**Comment by jonjohnsonjr** [comment]
> what about kind cluster? it's not kubectl parameter, it's used to load image into right kind clusters.

I think it's a global flag for kubectl:

```
$ kubectl options | grep -C3 'cluster'
    --client-key='':
	Path to a client key file for TLS

    --cluster='':
	The name of the kubeconfig cluster to use

    --context='':
	The name of the kubeconfig context to use
```

But yeah for sideloading into kind, you should use `KIND_CLUSTER_NAME` 👍
