### ISSUE TITLE
failed to push multiarch image

### ISSUE THREAD

**Issue by jkhelil** [ko-build/ko#839]
when trying to build multiarch image, the push is failing.
using a simple main.go example
package main

import "fmt"

func main() {
	fmt.Println("====================")
	fmt.Println("=== hello! ===")
	fmt.Println("====================")
}
export KO_DOCKER_REPO=quay.io/jkhelil
ko build --platform=all

`➜  example git:(master) ✗ ko build --platform=all
2022/10/07 09:32:33 Using base distroless.dev/static:latest@sha256:e4e2f6cf994840a4efe868feed742d69f866f3b1333705a67117abaf39a04b52 for github.com/jkhelil/example
2022/10/07 09:32:34 Building github.com/jkhelil/example for linux/arm64
2022/10/07 09:32:34 Building github.com/jkhelil/example for linux/riscv64
2022/10/07 09:32:34 Building github.com/jkhelil/example for linux/arm/v7
2022/10/07 09:32:34 Building github.com/jkhelil/example for linux/arm/v6
2022/10/07 09:32:34 Building github.com/jkhelil/example for linux/amd64
2022/10/07 09:32:34 Building github.com/jkhelil/example for linux/s390x
2022/10/07 09:32:34 Building github.com/jkhelil/example for linux/ppc64le
2022/10/07 09:32:34 Building github.com/jkhelil/example for linux/386
2022/10/07 09:32:35 Publishing quay.io/jkhelil/example-8e10de8e47e0f4c72045c80b21ab7956:latest
2022/10/07 09:32:37 pushed blob: sha256:b322ba77d5f6670b35958ba3b73061f990c6f4349b193211cacefda12dae821c
2022/10/07 09:32:37 pushed blob: sha256:527cec41d928e30d7c1df3ed84df729fdfb6f6921e0bb47b4a575d8c8090066d
Error: failed to publish images: error publishing ko://github.com/jkhelil/example: writing sbom: PUT https://quay.io/v2/jkhelil/example-8e10de8e47e0f4c72045c80b21ab7956/manifests/sha256-e3ca02771c1b64040f80bd5e77eaf15a441ab275c0c7ce14f3487decc2b7e67d.sbom: MANIFEST_INVALID: manifest invalid; map[message:failed to parse manifest: manifest data does not match schema: 'spdx+json' is not one of ['application/vnd.oci.image.layer.v1.tar', 'application/vnd.oci.image.layer.v1.tar+gzip', 'application/vnd.oci.image.layer.v1.tar+zstd', 'application/vnd.oci.image.layer.nondistributable.v1.tar', 'application/vnd.oci.image.layer.nondistributable.v1.tar+gzip', 'application/vnd.dev.cosign.simplesigning.v1+json', 'application/vnd.dsse.envelope.v1+json', 'application/tar+gzip', 'application/vnd.cncf.helm.chart.content.v1.tar+gzip', 'application/vnd.oci.image.layer.v1.tar+gzip']

Failed validating 'enum' in schema['properties']['layers']['items']['properties']['mediaType']:
    {'description': 'The MIME type of the referenced manifest',
     'enum': ['application/vnd.oci.image.layer.v1.tar',
              'application/vnd.oci.image.layer.v1.tar+gzip',
              'application/vnd.oci.image.layer.v1.tar+zstd',
              'application/vnd.oci.image.layer.nondistributable.v1.tar',
              'application/vnd.oci.image.layer.nondistributable.v1.tar+gzip',
              'application/vnd.dev.cosign.simplesigning.v1+json',
              'application/vnd.dsse.envelope.v1+json',
              'application/tar+gzip',
              'application/vnd.cncf.helm.chart.content.v1.tar+gzip',
              'application/vnd.oci.image.layer.v1.tar+gzip'],
     'type': 'string'}

On instance['layers'][0]['mediaType']:
    'spdx+json']
2022/10/07 09:32:37 error during command execution:failed to publish images: error publishing ko://github.com/jkhelil/example: writing sbom: PUT https://quay.io/v2/jkhelil/example-8e10de8e47e0f4c72045c80b21ab7956/manifests/sha256-e3ca02771c1b64040f80bd5e77eaf15a441ab275c0c7ce14f3487decc2b7e67d.sbom: MANIFEST_INVALID: manifest invalid; map[message:failed to parse manifest: manifest data does not match schema: 'spdx+json' is not one of ['application/vnd.oci.image.layer.v1.tar', 'application/vnd.oci.image.layer.v1.tar+gzip', 'application/vnd.oci.image.layer.v1.tar+zstd', 'application/vnd.oci.image.layer.nondistributable.v1.tar', 'application/vnd.oci.image.layer.nondistributable.v1.tar+gzip', 'application/vnd.dev.cosign.simplesigning.v1+json', 'application/vnd.dsse.envelope.v1+json', 'application/tar+gzip', 'application/vnd.cncf.helm.chart.content.v1.tar+gzip', 'application/vnd.oci.image.layer.v1.tar+gzip']

Failed validating 'enum' in schema['properties']['layers']['items']['properties']['mediaType']:
    {'description': 'The MIME type of the referenced manifest',
     'enum': ['application/vnd.oci.image.layer.v1.tar',
              'application/vnd.oci.image.layer.v1.tar+gzip',
              'application/vnd.oci.image.layer.v1.tar+zstd',
              'application/vnd.oci.image.layer.nondistributable.v1.tar',
              'application/vnd.oci.image.layer.nondistributable.v1.tar+gzip',
              'application/vnd.dev.cosign.simplesigning.v1+json',
              'application/vnd.dsse.envelope.v1+json',
              'application/tar+gzip',
              'application/vnd.cncf.helm.chart.content.v1.tar+gzip',
              'application/vnd.oci.image.layer.v1.tar+gzip'],
     'type': 'string'}

On instance['layers'][0]['mediaType']:
    'spdx+json']`

**Comment by imjasonh** [comment]
This is https://github.com/ko-build/ko/issues/532

Pass --sbom=none and it should work
