### ISSUE TITLE
OCI images with annotations?

### ISSUE THREAD

**Issue by srenatus** [ko-build/ko#844]
Hello!

I'm trying to consume a ko-built OCI image [from another tool](https://bass-lang.org), and that one depends on having a tag, i.e. `org.opencontainers.image.ref.name` in the annotations of the OCI archive.

Having dug around a bit, that seems like it's not possible right now? I would have hoped that the `--tags` flag together with `--oci-layout-path` would do the trick, but it doesn't seem to 🤔 

(See https://github.com/opencontainers/image-spec/blob/main/image-layout.md#indexjson-file)

**Comment by srenatus** [comment]
I'm not sure, I'll have to check... Just had it fail without anything set so far... I'll get back to you

**Comment by srenatus** [comment]
FWIW adding the annotation, and using a recent-enough ko version (it seems distroless.dev/ko didn't have https://github.com/ko-build/ko/pull/776) made it work out fine: https://github.com/srenatus/opa-x/blob/main/ko.bass. There, I'm just adding a "latest" ref name, because it's enough to make it work.

**Comment by developer-guy** [comment]
Hello @srenatus, is this problem can be related to this one?

> https://github.com/ko-build/ko/pull/870
