### ISSUE TITLE
importpath is not supported

### ISSUE THREAD

**Issue by cn007b** [ko-build/ko#849]
#### Problem

My env:
````sh
ko version:  0.12.0
os: darwin
````

When run next command:
````sh
ko publish ./main.go --tags 20221013
````
it returns error:
````sh
Error: failed to publish images: importpath "ko://command-line-arguments" is not supported: importpath is not `package main`
2022/10/13 23:47:07 error during command execution:failed to publish images: importpath "ko://command-line-arguments" is not supported: importpath is not `package main`
````
When run same command but without `./`:
````sh
ko publish main.go --tags 20221013
````
all works as expected.

#### Suggestion

Maybe it makes sense to add support for `./main.go`, WDYT?

**Comment by imjasonh** [comment]
Can you describe your environment a bit more?

I would expect this to work if you're in the root directory of a [Go module](https://go.dev/blog/using-go-modules), or [inside `$GOPATH`](https://go.dev/doc/gopath_code)

If not, if you run `go mod init github.com/cn007b/blah` and try `ko build` again, does it work?

The fundamental problem is that without being in a Go module or on `GOPATH`, Go and `ko` don't know what to call your code -- how to reference it later. The `command-line-arguments` string you see doesn't come from `ko`, it actually seems to come from [`x/tools/go/packages`](https://pkg.go.dev/golang.org/x/tools/go/packages), which `ko` calls to figure out what to call your code. The `command-line-arguments` string seems to indicate that Go doesn't know what to call it, and so you end up with that obscure string.

I'd run `go mod init <whatever import path you want>` and try again, and you should see logs indicating that Go and `ko` now know how to refer to your code, and can build and publish an image accordingly.

**Comment by cn007b** [comment]
Here simplified structure of my project:
````
repo
├── 🗂 cmd
│   ├── 🗂 http-app
│   │   └── main.go
│   └── 🗂 grpc-app
│       └── main.go
├── 🗂 internal
└── go.mod
````
I'm following this [layout](https://github.com/golang-standards/project-layout).
When run:
````sh
go run cmd/http-app/main.go
go run ./cmd/http-app/main.go

go build -o httpapp cmd/http-app/main.go
go build -o httpapp ./cmd/http-app/main.go
````
all works correctly,
that's why I've decided that next commands should work as well:
````sh
ko publish ./cmd/http-app/main.go --tags 20221013
Error: failed to publish images: importpath "ko://command-line-arguments" is not supported: importpath is not `package main`
2022/10/14 18:13:53 error during command execution:failed to publish images: importpath "ko://command-line-arguments" is not supported: importpath is not `package main`

ko publish cmd/http-app/main.go --tags 20221013
Error: failed to publish images: importpath "ko://cmd/http-app/main.go" is not supported: importpath is not `package main`
2022/10/14 18:14:06 error during command execution:failed to publish images: importpath "ko://cmd/http-app/main.go" is not supported: importpath is not `package main`

cd cmd/http-app && ko publish ./main.go --tags 20221013
Error: failed to publish images: importpath "ko://command-line-arguments" is not supported: importpath is not `package main`
2022/10/14 18:14:18 error during command execution:failed to publish images: importpath "ko://command-line-arguments" is not supported: importpath is not `package main`
````
but they won't, as you can see, fix in this case - omit `./`:
````sh
cd cmd/http-app && ko publish main.go --tags 20221013
````
now it works as expected.

**Comment by imjasonh** [comment]
Thanks for that clarification.

In general `ko` expects to be given a directory path, not a file path. So in your case that would be

```
ko build ./cmd/http-app
ko build ./cmd/grpc-app
```

or 

```
cd ./cmd/http-app && ko build
```

The reason being that there may be other files than `main.go` in there, so it's really more correct to think of it as the directory and not any particular file.

It might be better to make this expectation explicit in `ko`, and warn or reject file paths instead of trying to build them and failing with this cryptic error message.
