### ISSUE TITLE
Build from source currently broken

### ISSUE THREAD

**Issue by nsmith5** [ko-build/ko#857]
```
$ go install -v github.com/google/ko@latest
go: github.com/google/ko@latest: github.com/google/ko@v0.12.0 requires
	github.com/sigstore/cosign@v1.11.0 requires
	github.com/letsencrypt/boulder@v0.0.0-20220723181115-27de4befb95e requires
	github.com/honeycombio/beeline-go@v1.1.1 requires
	github.com/gobuffalo/pop/v5@v5.3.1 requires
	github.com/mattn/go-sqlite3@v2.0.3+incompatible: reading github.com/mattn/go-sqlite3/go.mod at revision v2.0.3: unknown revision v2.0.3
```

**Comment by nsmith5** [comment]
Building head seems happy so maybe not an issue anymore, but this makes the README lead to a sad experience of breakage so I thought I'd report anyways! Feel free to close if this is yesterdays bug and just waiting on release.

**Comment by imjasonh** [comment]
Weird! I'm not able to reproduce with `go install -v github.com/google/ko@latest`.

It looks like go-sqlite3 v2.0.3 was a mistake. It's [retracted](https://pkg.go.dev/github.com/mattn/go-sqlite3?tab=versions) along with other v2 versions, and their readme says

> Latest stable version is v1.14 or later, not v2.
> ~~NOTE: The increase to v2 was an accident. There were no major changes or features.~~

but all of that seems to have happened years ago, so I don't know why it would cause problems now.

🤷
