### ISSUE TITLE
Can `ko build` work without `go build`?

### ISSUE THREAD

**Issue by FFengIll** [ko-build/ko#877]
ko works very well with my go app, and I have reviewed the ko implementation in recent.

I believe `ko build` has implemented **a function to create image layer (efficiently)** with `go build artifact` and `KO_DATA_PATH`,
then I want to ask if ko can work **without** `go build`.

If it does, then we could make image with **arbitrary content** and utilize the performance from ko.
Furthermore, some extra build stages could get involve and contribute to the image layer if the above is possible.

**Comment by imjasonh** [comment]
No, `ko` invokes `go build` using [`os/exec`](https://pkg.go.dev/os/exec), and puts the output into a layer. It also calls other `go` commands to list packages, and list dependencies to generate SBOMs.

If you're interested in a tool that simply adds pre-built packages to an image, you might be interested in [`crane`](https://github.com/google/go-containerregistry/blob/main/cmd/crane/), which can be used to [add existing files to an image](https://github.com/google/go-containerregistry/blob/main/cmd/crane/recipes.md#bundle-directory-contents-into-an-image). It's built using the same libraries as `ko`, by most of the same people.

If you want to use those with `ko`, you could use `crane` to append arbitrary content to an image, then use that image as the base image in `ko`, which would give you a layered image containing all the contents, and your Go app.

If you want to write a new tool in Go, you can use the underlying library, [go-containerregistry](https://github.com/google/go-containerregistry/), which has methods to interact with remote registries, and mutate images (e.g., to append layers), all without a Docker daemon.

If you want to build this in another language, there are other implementations, but I'm not familiar enough with any to recommend them.
