### ISSUE TITLE
allow only generating binary

### ISSUE THREAD

**Issue by grosser** [ko-build/ko#880]
I want to use the binary ko builds locally, but I don't have docker installed.
Allow a '--no-image' option or a way to leave the binary on disk after ko is done so I can use it directly.
(we use a tool that is configured via `ko` and don't want to re-invent this with `go build`)

**Comment by imjasonh** [comment]
You can extract a file from an image using [`crane`](https://github.com/google/go-containerregistry/blob/main/cmd/crane/):

```
crane export $img - | tar -Oxf - /ko-app/$app > $app
```

For example:

```
crane export ghcr.io/ko-build/ko - | tar -Oxf - /ko-app/ko > ko
```

or

```
crane export gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.25.0 - | tar -Oxf - /ko-app/controller > controller
```

https://github.com/google/go-containerregistry/blob/main/cmd/crane/recipes.md#extract-a-single-file-from-an-image

---

Another option, if you use `KOCACHE`, is that the built binary should be in that directory ready to be reused:

```
$ KOCACHE=/tmp/kocache ko build ./cmd/foo
$ file /tmp/kocache/bin/${IMPORT_PATH}/linux/amd64/out
...ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked...
```

**Comment by grosser** [comment]
the KOCACHE approach works alright 👍
