### ISSUE TITLE
Change resulting image name

### ISSUE THREAD

**Issue by lucasoares** [ko-build/ko#892]
Hello.

I know there was issues before about the image name, but I think the issue I'm addressing was not solved by them.

I have main files for applications with the following name pattern: `some_name_with_underscore.go`.

I'd like to create an image and to have its name in the following pattern: `repo/some-name-with-underscore`

Currently is impossible to use `ko` and change resulting image name like that, right?

Thanks.

**Comment by leongross** [comment]
Maybe one workaround could be to extract the image layer(s) in tar format and import them again under the name that you wish.

**Comment by imjasonh** [comment]
Yeah, `--bare` and `KO_DOCKER_REPO` are probably the correct solution to this.

That, or building and pushing the image to somewhere, then copying it with something like [`crane copy`](https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane_copy.md)

```
crane copy <ko-built-image-location> username/image
```

**Comment by lucasoares** [comment]
But guys, the real question is: why it is so difficult to add a new parameter `KO_DOCKER_IMAGE_NAME` instead of using `--bare` and `KO_DOCKER_REPO`?

I don't know if there is something I'm missing but this would be the best approach to this, to let users set the image name they want without complicating things with `--bare` and `KO_DOCKER_REPO`

:thinking:

**Comment by jonjohnsonjr** [comment]
If you're using `ko` to build/deploy multiple things at the same time, you're going to need multiple image names. E.g. [this benchmark](https://github.com/knative/serving/blob/c832f358b92f50ebf1fa9a35b08434537f36fd16/test/performance/benchmarks/scale-from-zero/continuous/scale-from-zero-direct.yaml#L47-L58) builds two images, so you need two different image names in order to publish them.

**Comment by lucasoares** [comment]
> If you're using `ko` to build/deploy multiple things at the same time, you're going to need multiple image names. E.g. [this benchmark](https://github.com/knative/serving/blob/c832f358b92f50ebf1fa9a35b08434537f36fd16/test/performance/benchmarks/scale-from-zero/continuous/scale-from-zero-direct.yaml#L47-L58) builds two images, so you need two different image names in order to publish them.

I'm not =)
