### ISSUE TITLE
Include a standalone directory (for templates) with ko build

### ISSUE THREAD

**Issue by jimangel** [ko-build/ko#894]
I'm trying to include a directory in addition to my go binary when I run `ko build`.

In my case it's a folder named `templates/` containing `.tmpl` files for generation & output. Similar to https://stackoverflow.com/a/51866231, which is solved with:

```
COPY --from=0 /go/bin/hello-app/ .
COPY --from=0 /go/src/hello-app/templates ./templates
```

In a Dockerfile. Also, it's possible I'm missing an obvious way to make them a dependency of my go app...

In any event, if someone could let me know what I'm missing. If it's already possible, I'm happy to PR some additional docs around using the setting.

**Comment by imjasonh** [comment]
In ko this would be done with a `kodata` directory (https://ko.build/features/static-assets/), which could be a symlink to your `templates` directory. Then those files would be accessible inside your container at `$KO_DATA_PATH`.

There's also been a [request](https://github.com/ko-build/ko/pull/867) to have this supported differently, so it doesn't depend on the convention that the directory is named `symlink`.

**Comment by jimangel** [comment]
This is perfect, thanks! I'll close the issue. I'm not sure how I missed that in the docs. I hope this issue also helps folks searching for "standalone directory" vs. "static assets" 😅

Think it's worth boosting a blurb in the GitHub README? (happy to /assign me)

FWIW solving this by switching a am64/arm64 build from `ko` to `buildx` increased my GitHub Actions from 3 minutes to **25 minutes (733.33% [[ref](https://github.com/jimangel/k8s-2-gsm/commit/ddaa94f40c1a06cc37ff4751025d8df9cd3b46c2)])**. To be fair, I also was doing 2 stage builds + `go vet -v` in the Dockerfile.

Nevertheless, glad to solve this with a symlink at the cost of a 25m build lol, thanks!
