### ISSUE TITLE
CNCF TAG-Runtime Discussion/Presentation (?)

### ISSUE THREAD

**Issue by raravena80** [ko-build/ko#906]
Hello ko team,

I'm one of the co-chairs of the CNCF TAG-Runtime. I believe you had an agenda item to present the project in our meeting.  For example, it would be great to learn things like the roadmap, tech, community, general overview of the project.

Feel free to add it to our [agenda](https://bit.ly/cncf-tag-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com) at your convenience. 

Thanks!

**Comment by imjasonh** [comment]
Sorry for not seeing this issue earlier. I'd love to come present! I added myself to the Jan 5 agenda, feel free to move me around if you need to.

**Comment by developer-guy** [comment]
I think we can now close this as the presentation has been made by @imjasonh  ☝️

* YouTube Video: _https://youtu.be/anJpjqYT-o0_
* Social Media Announcement: _https://twitter.com/developerguyba/status/1612856948130549779?s=20_
* Slides: _https://docs.google.com/presentation/d/1usK7tgWu_fn8IPQlMzcE5KPMaob1AwT5A__Nok3OT4o/edit#slide=id.p_

**Comment by developer-guy** [comment]
I moved the ko's presentation to the `Completed Items` in the [agenda](https://bit.ly/cncf-tag-runtime-meeting-notes).

PTAL @raravena80
