### ISSUE TITLE
enable guessing local environment os/arch by using local as option for platform flag

### ISSUE THREAD

**Issue by developer-guy** [ko-build/ko#907]
Some of the tools are supporting to accept `local` as a value for their `platform` flag, such as Docker Buildx, regctl. So, can we do the same thing for ko instead of throwing an error like the following:

```shell
$ KO_DOCKER_REPO=docker.io/devopps ko build -B  --platform local --tags buildinfo .
Error: failed to publish images: error building "ko://github.com/developer-guy/hello-world-ko": no matching platforms in base image index
2022/12/15 15:08:57 error during command execution:failed to publish images: error building "ko://github.com/developer-guy/hello-world-ko": no matching platforms in base image index
```

/cc @dentrax

**Comment by developer-guy** [comment]
We can have something like the following:

https://github.com/regclient/regclient/tree/7b8fc70dedc316a5ed4484a0e5f5b428751ef907/types/platform

/cc @imjasonh @sudo-bmitch

**Comment by imjasonh** [comment]
I like --platform=local.

Should we also default to the local platform when publishing to the local daemon? (--local or ko.local)

**Comment by imjasonh** [comment]
Sounds like buildx defaults to the local platform: https://docs.docker.com/engine/reference/commandline/buildx_build/#platform

I think this would be a breaking change for ko though, especially since so many folks (myself included) build on M1 Mac and publish to run on an amd64 cluster.
