### ISSUE TITLE
Add ko maintainers as org admins

### ISSUE THREAD

**Issue by imjasonh** [ko-build/ko#915]
Maintainers listed here: https://github.com/ko-build/ko/blob/main/MAINTAINERS.md

- @jonjohnsonjr (already an org admin?)
- @imjasonh 
- @mattmoor 

Along with https://github.com/ko-build/ko/issues/914 this will let us perform some CNCF onboarding tasks and import related repos.

**Comment by mchmarny** [comment]
Makes sense, let me add these.

**Comment by mchmarny** [comment]
done
