### ISSUE TITLE
add all the links related to the ko to ko.build website

### ISSUE THREAD

**Issue by developer-guy** [ko-build/ko#925]
Many articles, videos, conference talks, presentations, etc., are available related to the ko project. These are super important for the new people who want to learn more about the ko project in addition to the getting-started documentation of the project. 

So, I'm proposing that it'd be better to create another page to include all these notable links about ko.

I can take the responsibility of creating that page ☝️

**Comment by imjasonh** [comment]
How would we organize and update this page? I don't want just a wall of undifferentiated links, and I don't want to get in the business of having to tell folks their link should go higher or lower than another, or isn't about `ko` "enough" to qualify.

I'm not saying no, I just wonder what would go on the page and how we can make sure it's useful.

**Comment by developer-guy** [comment]
I just thought it might be helpful to provide introductory blog posts, videos, workshops, etc. for people who might want to learn more about the use cases of ko in the ecosystem. I also do think that it might cause a positive impact on the community because people might want to be part of that "hall of fame", so they might start providing resources about ko.
