### ISSUE TITLE
Make `go` and `kubectl` version configurable

### ISSUE THREAD

**Issue by embano1** [ko-build/ko#926]
Currently, `ko` uses hardcoded values to retrieve the `go` and `kubectl` executables, e.g.

https://github.com/ko-build/ko/blob/453bf803e379696a0b9142c772402ba4599cff34/pkg/build/gobuild.go#L288

The desired behavior is to make those binary locations configurable, e.g. via `KO_GO_PATH` and `KO_KUBECTL_PATH`.
Alternatively, they could be specified in `.ko.yaml` but this might be overkill as setting these values are considered exceptional.

**Comment by imjasonh** [comment]
Let's start with `KO_GO_PATH`. AFAIK nobody's asked to be able to change the kubectl path. The naming is convenient because if we want to make it configurable in `.ko.yaml` we can just add a `go_path` field and Viper will pick up `KO_GO_PATH` for us.
