### ISSUE TITLE
cannot push to internal registry (on OSX)

### ISSUE THREAD

**Issue by chmouel** [ko-build/ko#939]
I am not really sure I can explain it but I can't seem being able to push to a local registry that is running on http, google-containerregistry seems to always try to push on https (it doesn't have any login on there):

```
$ env KO_DOCKER_REPO=localhost:5000 ko apply -f config -B --sbom=none --verbose
```

```
User-Agent: ko/0.12.0 go-containerregistry/v0.11.0
Accept-Encoding: gzip


2023/01/19 18:52:38 <-- net/http: TLS handshake timeout GET https://localhost:5000/v2/ (10.002996375s)
2023/01/19 18:52:38 <-- net/http: TLS handshake timeout GET https://localhost:5000/v2/ (10.002971458s)
2023/01/19 18:52:38 <-- net/http: TLS handshake timeout GET https://localhost:5000/v2/ (10.002608625s)
2023/01/19 18:52:41 --> GET https://localhost:5000/v2/
2023/01/19 18:52:41 GET /v2/ HTTP/1.1
Host: localhost:5000
User-Agent: ko/0.12.0 go-containerregistry/v0.11.0
Accept-Encoding: gzip
```

```
Error: error processing import paths in "config/500-watcher.yaml": error resolving image references: Get "https://localhost:5000/v2/": context canceled; Get "http://localhost:5000/v2/": context canceled
```

works fine when i do :

```
% curl localhost:5000/v2 -vL
# come back with a 200 and {}
```

even when i install a self certs and mount it as per https://docs.docker.com/registry/insecure/#use-self-signed-certificates

it still would not be able to push there (combined with --insecure-registry)

I workaround it with this script : 

```bash
#!/usr/bin/env bash
set -euxf
env KO_DOCKER_REPO=ko.local:5000 ko resolve -f config > /tmp/a.yaml
IMAGES=$(grep ko.local /tmp/a.yaml|sed 's/"//g;s/.*image: //')

for image in ${IMAGES};do
    pushimage=${image/ko.local/localhost:5000}
    docker tag ${image}  ${pushimage}
    docker push ${pushimage}
done

kubectl apply -f <(sed 's,ko.local,localhost:5000,g' /tmp/a.yaml)
```

which push to the internal docker and retag it and push to the local registry on container, which works fine..

This only happen on this OSX laptop, and I can't seem to have that issue on my Linux laptop or when we do this on CI: https://github.com/openshift-pipelines/pipelines-as-code/blob/main/hack/dev/kind/install.sh#L146

so I am not really sure what's going on, anyway logging this bug in case this script may help others....

**Comment by developer-guy** [comment]
Hello @chmouel, thanks for raising an issue! There should be a flag in ko to skip TLS verification on the registry named `--insecure-registry`. Can you please use this flag with your example?

**Comment by chmouel** [comment]
yup, i did use it!
