### ISSUE TITLE
ko creates "linux/amd64" base image on Mac M1

### ISSUE THREAD

**Issue by prietyc123** [ko-build/ko#946]
I am not really sure but I think there is a bug on `ko` while loading image to the node process. When I am trying to apply some [manifests](https://github.com/tektoncd/results/tree/main/config) using ko, it builds a base image of `linux/amd64` on Mac M1 and then it is not able to load those images to the node created.

```bash
#!/bin/bash

set -e

export KO_DOCKER_REPO=${KO_DOCKER_REPO:-"kind.local"}
export KIND_CLUSTER_NAME=${KIND_CLUSTER_NAME:-"tekton-results"}
[...]
kubectl kustomize "path-to-manifest" | ko apply -f -
```
The cluster is running perfectly
```
$ kind get clusters
tekton-results
```
**Error**
```
2023/01/26 15:46:11 Using base distroless.dev/static:latest@sha256:052a77bdcff373d829fb504c495782852946cb20f9f72385e771670d61b291f3 for github.com/tektoncd/results/cmd/api
2023/01/26 15:46:12 Using base distroless.dev/static:latest@sha256:052a77bdcff373d829fb504c495782852946cb20f9f72385e771670d61b291f3 for github.com/tektoncd/results/cmd/watcher
2023/01/26 15:46:13 Building github.com/tektoncd/results/cmd/api for linux/amd64
2023/01/26 15:46:13 Building github.com/tektoncd/results/cmd/watcher for linux/amd64
2023/01/26 15:46:17 Loading kind.local/api-b1b7ffa9ba32f7c3020c3b68830b30a8:86cb3936bb4dfa9b09a488a5a0e19de056cc2fda546ea860a11789e7cca9ca14
2023/01/26 15:46:17 Loading kind.local/watcher-83f971ea227fb24157c0c699b824a628:e752f7a6362e8e71f9984dedaa51891b92929244e86ed1fe9e7fedce904aecbc
error: no objects passed to apply
Error: error processing import paths in "-": error resolving image references: 
failed to load image to node "tekton-results-worker": command "docker exec --privileged -i tekton-results-worker ctr --namespace=k8s.io images import -" failed with error: exit status 1
ctr: image might be filtered out
```
After analysing the issue I was thinking whether creating an `x86` image instead would help. Might be by setting `GOARCH` env var to `arm64`. Other than that I am not getting much clue on this. Any help or thoughts are really appreciated.

**Comment by jonjohnsonjr** [comment]
We currently default to linux/amd64, but it might make sense to change that: https://github.com/ko-build/ko/issues/907

You can use the `--platform` flag to select an appropriate platform as well.

**Comment by prietyc123** [comment]
> You can use the --platform flag to select an appropriate platform as well.

yes it worked using `--platform`. Thanks.
