### ISSUE TITLE
Idea: Specify base image contents using apko

### ISSUE THREAD

**Issue by imjasonh** [ko-build/ko#954]
tl;dr:
```
defaultBaseImage: apko://path/to/base-image.yaml
```

Where `base-image.yaml` can be some valid apko YAML file, like this: https://github.com/chainguard-dev/apko/blob/main/examples/wolfi-base.yaml

When `ko` builds an image with an `apko://`-prefixed base image, it would first build the base using apko (as a library). The result is that `ko` can be used to build an image that contains OS packages like `curl`, `git`, etc.

**Comment by developer-guy** [comment]
It's worth noting that this operation will require `proot` or `bubblewrap`; am I right, @imjasonh?

**Comment by imjasonh** [comment]
Melange needs those, not apko. Apko _currently_ requires `apk` to be available, but that dependency will be dropped soon (🤞), which will make this change a lot easier to test and implement.

I might suggest waiting for that work to be done and released, otherwise it might be too painful to iterate on.

**Comment by developer-guy** [comment]
we made some code changes, I'm going to open a PR right now.
