### ISSUE TITLE
Can we use ko build with --tarball ?

### ISSUE THREAD

**Issue by eddycharly** [ko-build/ko#968]
I tried to use `ko build ... --tarball background-controller.tar.gz` but I don't see any tarball output.

Is there an example of outputting the image in an archive available somewhere ?

**Comment by imjasonh** [comment]
```
$ ko build --tarball out.tar
...
2023/02/27 11:19:56 Saving out.tar
$ ls -lh out.tar
-rw-r--r--  1 jason  staff    75M Feb 27 11:22 out.tar
```

I agree we should document this better, and have examples and probably more tests, but AFAIK `--tarball` should work.

The intention is that the resulting `.tar` file can be copied around and loaded into a Docker daemon with `docker load < out.tar`, or pushed with `crane push out.tar <registry>`. If there's another use case you had in mind that would be helpful too.

**Comment by eddycharly** [comment]
If i do that i receive:
```
Error: error creating publisher: KO_DOCKER_REPO environment variable is unset
```

**Comment by imjasonh** [comment]
Oh, yes. `ko build --tarball` still pushes the image, which requires you to tell `ko` _where_ to push the image. If you want to skip pushing but still generate the tarball, `ko build --tarball out.tar --push=false`.

**Comment by eddycharly** [comment]
I may have a flag that prevents it to work, my make target is:
```
.PHONY: ko-build-background-controller
ko-build-background-controller: $(KO) ## Build background controller local image (with ko)
	@echo Build background controller local image with ko... >&2
	@LD_FLAGS=$(LD_FLAGS_DEV) KOCACHE=$(KOCACHE) KO_DOCKER_REPO=$(KO_REGISTRY) \
		$(KO) build --push=false ./$(BACKGROUND_DIR) --preserve-import-paths --tags=$(IMAGE_TAG_DEV) --platform=$(LOCAL_PLATFORM) --tarball out.tar
```

Any idea what could cause the issue ?
