### ISSUE TITLE
Use `provenance-name` output

### ISSUE THREAD

**Issue by ianlewis** [ko-build/ko#982]
The [`attestation-name`](https://github.com/ko-build/ko/blob/2860fcf5eec19d9716aaa9c26394da0b1e7b13de/.github/workflows/release.yml#L95) output from provenance generation is [deprecated](https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/generic/README.md#workflow-outputs). It should be updated to `provenance-name`.

**Comment by ianlewis** [comment]
I forgot to make this change on #980

**Comment by developer-guy** [comment]
May I do that ?

**Comment by ianlewis** [comment]
> May I do that ?

of course :)
